services:
  postgres:
    image: postgres:16
    container_name: maspatas-postgres
    environment:
      POSTGRES_USER: maspatas
      POSTGRES_PASSWORD: maspatas
      POSTGRES_DB: maspatas
    ports:
      - "5432:5432"
    volumes:
      - maspatas_pg_data:/var/lib/postgresql/data

volumes:
  maspatas_pg_data:
