services:
  mongo:
    image: mongo:7
    container_name: maspatas-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: maspatas
      MONGO_INITDB_ROOT_PASSWORD: maspatas
    volumes:
      - maspatas_mongo_data:/data/db

volumes:
  maspatas_mongo_data:
